# Generated by Django 3.2.3 on 2024-02-08 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_favourite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение должно быть не менее 1 минуты'), django.core.validators.MaxValueValidator(360, message='Максимальное значение должно быть не более 360 минут')], verbose_name='Длительность приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество не менее 1'), django.core.validators.MaxValueValidator(999, message='Максимальное количество не более 999')], verbose_name='Количество'),
        ),
    ]
