# Generated by Django 3.2.3 on 2024-02-05 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240205_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите правильное значение.', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнейм'),
        ),
    ]
